[tool.poetry]
name = "nudeform"
version = "0.1.0"
description = ""
authors = ["DFreireF <D.FreireFernandez@gsi.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["setuptools", "wheel"]
build-backend ="setuptools.build_meta"
